apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-from-pr-binding
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositoryurl
    value: $(body.repository.git_url)
