apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-from-pr-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: image-$(uid)
    spec:
      type: image
      params:
        - name: url
          value: quay.io/kmcdermo/hello-go:$(params.gitrevision)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: build-pipeline-run-$(uid)
    spec:
      serviceAccountName: demo-sa
      pipelineRef:
        name: build-pipeline
      resources:
        - name: source-repo
          resourceRef:
            name: git-source-$(uid)
        - name: runtime-image
          resourceRef:
            name: image-$(uid)
